swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /dbpeople:
    get:
      operationId: "db_people.read"
      tags:
        - "People from DB"
      summary: "A list of people from a db"
      responses:
        200:
          description: "Successful db access"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                surname:
                  type: "string"
  /people:
    get:
      operationId: "people.read"
      tags:
        - "People"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
